## 开发环境配置信息

#数据库信息 url中相关属性
DbPort: 1521
DbServiceName: ORCL
DbServiceNameType: service_name
DbServerAddr: localhost
DbServerName: DEDICATED

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  # 设置静态文件路径，js,css等
  mvc:
    static-path-pattern: /**
  resource:
    static-locations: classpath:/static/,classpath:/public/
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure


  #热部署生效(注: SpringBoot 配置完毕后,还需开启idea自动编译,eclipse是默认开启)
  devtools:
    restart:
      enabled: true
      #设置重启目录
      additional-paths: src/main/java
  ## 数据库信息
  datasource:
    url: jdbc:oracle:thin:@(description=(address=(host=${DbServerAddr})(protocol=tcp)(port=${DbPort}))(connect_data=(${DbServiceNameType}=${DbServiceName})(server=${DbServerName}))))
    username: lyy
    password: 'lyy900915'  #datasource
    driver-class-name: oracle.jdbc.OracleDriver
    ## 数据库连接池配置,指定druid为数据源,如果不加,则默认的数据源为:org.apache.tomcat.jdbc.pool.DataSource
    type: com.alibaba.druid.pool.DruidDataSource
    #初始化连接大小
    initialSize: 5
    #最小连接池数量
    minIdle: 5
    #最大连接池数量
    maxActive: 20
    ## 连接等待超时时间
    maxWait: 60000
    ## 配置隔多久进行一次检测(检测可以关闭的空闲连接) 毫秒
    timeBetweenEvictionRunsMillis: 60000
    ## 配置连接在池中的最小生存时间 毫秒
    minEvictableIdleTimeMillis: 300000
    #测试连接
    validationQuery: SELECT 1 FROM DUAL
    #申请连接的时候检测，建议配置为true，不影响性能，并且保证安全性
    testWhileIdle: true
    #获取连接时执行检测，建议关闭，影响性能
    testOnBorrow: false
    #获取连接时执行检测，建议关闭，影响性能
    testOnReturn: false
    ## 打开PSCache，并且指定每个连接上PSCache的大小(PSCache对支持游标的数据库性能提升巨大，oracle建议开启，mysql下建议关闭)
    poolPreparedStatements: true
    #开启poolPreparedStatements后生效
    maxPoolPreparedStatementPerConnectionSize: 20
    #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    #通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    #连接出错后再尝试连接0次
    connectionErrorRetryAttempts: 0
    #数据库服务宕机自动重连机制
    breakAfterAcquireFailure: true

## 如果jar 包运行 则开启以下配置
server:
  ## 设定编码
  tomcat:
    uri-encoding: UTF-8
  port: 9092
  ## 指定访问项目路径的项目名
  servlet:
    context-path: /sjyxt
      ## 约定传参编码格式
    encoding:
      force: true
      charset: UTF-8
      enabled: true

mybatis:
  # spring boot集成mybatis的方式打印sql,开发调试开启即可
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

## mybatis分页插件
pagehelper:
  helperDialect: oracle
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  page-size-zero: true

## druid监控地址:http://127.0.0.1:8517/data-source-serve
## Druid数据库连接池监控访问配置,loginUsername:登录用户名 loginPassword:登录密码
## allow:允许访问的IP白名单(多个IP用逗号分开),deny:访问数据库连接池监控黑名单IP
## resetEnable:是否能够重置数据
oracleDruid:
  loginUsername: datasourceserve20200413!@##@!
  loginPassword: datasourceserve20200413!@##@!
  #allow: 127.0.0.1
  #deny: 192.168.1.1
  resetEnable: false

# 秘钥
#db_secretKey: 83abe08f8b1040b2a75b6faf29384cfd

swagger:
  production: false
  basic:
    enable: true
    username: admin
    password: admin



